const GET_BOOKS_LIST = 'GET_BOOKS_LIST';
const GET_BOOKS_LIST_SUCCESS = 'GET_BOOKS_LIST_SUCCESS';
const GET_BOOKS_LIST_ERROR = 'GET_BOOKS_LIST_ERROR';
const UNAUTH_USER = 'UNAUTH_USER';


export {
  GET_BOOKS_LIST, GET_BOOKS_LIST_SUCCESS, GET_BOOKS_LIST_ERROR, UNAUTH_USER,
};
